spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - enabled: false
      active-directory:
        enabled: false
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      base-url: ${ANTHROPIC_BASE_URL}
