name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: test/package-lock.json
      - name: Install dependencies
        working-directory: test
        run: npm ci
      - name: Install Playwright browsers
        working-directory: test
        run: npx playwright install chromium --with-deps
      - name: Setup test environment and start Docker Compose
        run: scripts/compose_up.sh
      - name: Run Playwright tests
        working-directory: test
        run: npx playwright test
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results
          path: test/test-results
      - run: docker compose logs
        if: always()

  publish:
    runs-on: ubuntu-latest
    needs: test-e2e
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get next version
        id: get_next_version
        uses: mucsi96/get-next-version@main
        with:
          prefix: 'v'

      - name: Login to GitHub Container Registry
        if: steps.get_next_version.outputs.hasNextVersion == 'true'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server image
        if: steps.get_next_version.outputs.hasNextVersion == 'true'
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/skeleton-app-server:${{ steps.get_next_version.outputs.version }} server
          docker push ghcr.io/${{ github.repository_owner }}/skeleton-app-server:${{ steps.get_next_version.outputs.version }}

      - name: Build and push client image
        if: steps.get_next_version.outputs.hasNextVersion == 'true'
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/skeleton-app-client:${{ steps.get_next_version.outputs.version }} client
          docker push ghcr.io/${{ github.repository_owner }}/skeleton-app-client:${{ steps.get_next_version.outputs.version }}

      - name: Create release
        if: steps.get_next_version.outputs.hasNextVersion == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v-${{ steps.get_next_version.outputs.version }}
          generate_release_notes: true
